### ISSUE TITLE
Problem with searching for documents

### ISSUE THREAD

**Issue by pjazdzewski1990** [techblue/alfresco-restclient#14]
Hi. Great work with the REST client - it's really simple to use and get things done quickly. 
I'm using it for a small project and I've stumbled onto an issue. 
I want to search for a folder with a specific name and can't find any good resources on how to do that. Maybe you could give me some hints how it could be done with alfresco-restclient (or Alfresco API in general)? 
Assuming that the name of the folder is "foo" and `rootFolder` is the `nodeId` of the folder in which "foo" should exist, I would like to get the `nodeId` of the "foo" folder. I've tried like this:
```
val folderService = new FolderService("http://localhost:8085", ticket)
folderService.searchFolder(rootFolder, """ @cm\:name:"foo" """)
```
But it gives me a 404 with
```
The Web Script /alfresco/service/api/search/folder/workspace/SpacesStore/4e8f11a8-8ca2-4613-b5d7-15ba0787e3fb has responded with a status of 404 - Not Found.

404 Description:	Requested resource is not available.
 
Message:	06260034 Script url /api/search/folder/workspace/SpacesStore/4e8f11a8-8ca2-4613-b5d7-15ba0787e3fb does not map to a Web Script.
Server:	Enterprise v5.1.0 (.5 r127092-b59) schema 9,018
Time:	Jul 26, 2016 1:50:08 PM
```
Any ideas, suggestions or resources I could look up? 
Thank you
cc: @georgekankava @dheerajarora

**Comment by dheerajarora** [comment]
Hi Patryk, 

Thanks for your message. I looked at the problem and it seems like the supporting web scripts do not present in your alfresco instance. I'll commit the cmisSearchScripts in the resources folder for you. You need to add those scripts in your alfresco instance and it should work fine then. 

Also, this needs to modified a bit to support cmis query generically (not specifically folder search). I'll change this and update you here.

Thanks
Dheeraj

**Comment by pjazdzewski1990** [comment]
@dheerajarora Any progress on the scripts? 
Thanks for the help

**Comment by dheerajarora** [comment]
Just committed a fix for the above, after placing the webscripts (src/main/resources/uk/co/techblue/alfresco/webscripts/searchfolder) into your alfresco instance.

folderService.searchFolder("<<parent node id>>", "cmis:name IN ('foo', 'bar')").

Hope this helps.

Thanks
Dheeraj
